[package]
name = "edgeware-primitives"
version = "2.0.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
primitives = { package = "sp-core", git = "https://github.com/drewstone/substrate.git", default-features = false }
sr-primitives = { package = "sp-runtime", git = "https://github.com/drewstone/substrate.git", default-features = false }

[dev-dependencies]
substrate-serializer = { package = "sp-serializer", git = "https://github.com/drewstone/substrate.git" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"primitives/std",
	"sr-primitives/std",
]