[package]
name = "edge-voting"
version = "1.0.0"
authors = ["Drew Stone <drew@commonwealth.im>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
safe-mix = { version = "1.0", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
rstd = { package = "sp-std", git = "https://github.com/drewstone/substrate.git", default-features = false }
sr-primitives = { package = "sp-runtime", git = "https://github.com/drewstone/substrate.git", default-features = false }
support = { package = "frame-support", git = "https://github.com/drewstone/substrate.git", default-features = false }
system = { package = "frame-system", git = "https://github.com/drewstone/substrate.git", default-features = false }
balances = { package = "pallet-balances", git = "https://github.com/drewstone/substrate.git", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/drewstone/substrate.git", default-features = false }
substrate-primitives = { package = "sp-core", git = "https://github.com/drewstone/substrate.git", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"safe-mix/std",
	"codec/std",
	"rstd/std",
	"sr-primitives/std",
	"support/std",
	"system/std",
	"balances/std",
]
